apiVersion: v1
kind: Pod
metadata:
  name: psa-demo-pod-priv
spec:
  containers:
    - name: psa-demo-pod
      image: nginx:latest
      resources:
        requests:
          cpu: '0.5'
          memory: '256Mi'
        limits:
          cpu: '1'
          memory: '512Mi'
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        capabilities:
          add: ['NET_ADMIN', 'SYS_TIME']
