kind: Pod
apiVersion: /v1
metadata:
  name: pause
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.1
      resources:
        requests:
          cpu: '0.5'
          memory: '256Mi'
        limits:
          cpu: '1'
          memory: '512Mi'
