apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-deployment
  labels:
    app: pause
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.1
          resources:
            requests:
              cpu: '0.5'
              memory: '256Mi'
            limits:
              cpu: '1'
              memory: '512Mi'
