kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store-inline
spec:
  serviceAccountName: aws-node
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - name: container-day-demo-secret
          mountPath: '/mnt/secrets-store'
          readOnly: true
      resources:
        requests:
          cpu: '0.5'
          memory: '256Mi'
        limits:
          cpu: '1'
          memory: '512Mi'
  volumes:
    - name: container-day-demo-secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: 'aws-secrets'
